[package]
name = "parsluchtkwaliteit"
version = "0.1.0"
authors = ["jnve11"]

[dependencies]
csv = "1.0.0-beta.5"
serde_json = "1.0.0"
serde ="*"
carboxyl = "0.2.1"
serde_derive = "*"
base64 = "0.9.0"
